[package]
name = "evefrontier-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
anyhow = "1.0"
evefrontier-lib = { path = "../evefrontier-lib" }
directories = "4.0"
dirs = "5.0"
